### ISSUE TITLE
Exception for larger input

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#33]
I got this error when running the central oregon landcover section 75% of the way through the processing tiles step:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/cbroms/Documents/geopolygonize/src/geopolygonize.py", line 156, in <module>
    cli()
  File "/Users/cbroms/Documents/geopolygonize/venv-dev/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbroms/Documents/geopolygonize/venv-dev/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/cbroms/Documents/geopolygonize/venv-dev/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbroms/Documents/geopolygonize/venv-dev/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbroms/Documents/geopolygonize/src/geopolygonize.py", line 150, in cli
    raise e
  File "/Users/cbroms/Documents/geopolygonize/src/geopolygonize.py", line 145, in cli
    gdf = rz.process()
          ^^^^^^^^^^^^
  File "/Users/cbroms/Documents/geopolygonize/src/utils/tiler.py", line 102, in process
    self._process_tiles(all_tile_parameters)
  File "/Users/cbroms/Documents/geopolygonize/src/utils/tiler.py", line 81, in _process_tiles
    for _ in tqdm(
  File "/Users/cbroms/Documents/geopolygonize/venv-dev/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
shapely.errors.GEOSException: TopologyException: side location conflict at -43954.42796256701 47360.496962901969. This can occur if the input geometry is invalid.
```

**Comment by slz4025** [comment]
The exception occurs in tile [2400:2500, 2400:2500].

**Comment by slz4025** [comment]
Original
![orig](https://github.com/rainflame/geopolygonize/assets/31460433/1629beab-4fe3-40e9-a66b-098664a0965b)

Cleaned
![cleaned](https://github.com/rainflame/geopolygonize/assets/31460433/f6ba61fc-d240-4c8b-ad36-f4b6d2cd0226)

The cleaned output is sketchy, an occurrence of #28 probably.

Despite this, the vectorizer _should_ be robust.

**Comment by slz4025** [comment]
Fixed by #43.

**Comment by slz4025** [comment]
Turns out it still errors out on broken file descriptor.

**Comment by slz4025** [comment]
Above fixes logging issue as well as underlying issue of incorrectly referenced Exception. This reveals the following error encountered after stitching:
```
geopolygonize encountered error: TopologyException: side location conflict at 28048.042625668284 -24642.797154745087. This can occur if the input geometry is invalid.
```

**Comment by slz4025** [comment]
Tile directory: /tmp/tmplg9w37n9
New error:
```
Processing tiles:  75%|███████▌  | 192/255 [08:02<01:40,  1.60s/it]Encountered GEOSException: TopologyException: side location conflict at -43954.42796256701 47360.496962901969. This can occur if the input geometry is invalid.
Processing tiles: 100%|██████████| 255/255 [10:02<00:00,  2.36s/it]
Stitching tiles: 100%|██████████| 255/255 [02:04<00:00,  2.05it/s]
geopolygonize encountered error: Cannot determine common CRS for concatenation inputs, got ['North_American_1983_Albers', 'North_American_1983_Albers']. Use `to_crs()` to transform geometries to the same CRS before merging.
```

**Comment by slz4025** [comment]
Details of run:
- Tile directory: /tmp/tmprga3ure1

**Comment by slz4025** [comment]
Similar to before, the issue occurs when we perform the `unary_union` in `unify_by_label` when we create the final output shapefile. We might have to revisit the tactic to identify bad geometries after each modification and fix them somehow.

**Comment by slz4025** [comment]
Investigate tile [2400:2500, 2400:2500] and see if it _looks_ odd.

**Comment by cbroms** [comment]
The issue appears to be that the polygon is invalid. 
<img width="498" alt="Screenshot 2023-12-01 at 10 55 31 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/8d0dc3e0-15eb-4590-8513-d0300790c354">
<img width="278" alt="Screenshot 2023-12-01 at 10 55 37 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/c0041e53-98c4-464c-a7cc-e309e645f98b">
<img width="645" alt="Screenshot 2023-12-01 at 10 56 01 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/f001dae3-dd2c-4b40-a19b-5a43de7fc892">

**Comment by cbroms** [comment]
Here's another common example of broken geometries, this time from the sisters tiles:
<img width="430" alt="Screenshot 2023-12-01 at 10 57 34 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/0080635e-0df0-4ec8-a240-c91c607654d0">
<img width="508" alt="Screenshot 2023-12-01 at 10 58 15 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/845f1fca-253c-4b27-ac1f-541194649ef2">
<img width="563" alt="Screenshot 2023-12-01 at 10 58 30 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/58a3081b-0462-4bbc-86ab-c1b110cc7f85">

**Comment by slz4025** [comment]
So there are two types of invalid geometries:
1. A polygon has self-intersections that create a new area.
2. A polygon has a "loose segment".
While ideally we should fix both types of geometries non-destructively, it is the former type of invalid geometry that was associated with tile [2400:2500, 2400:2500] and most likely caused the `unary_union` to fail.
