### ISSUE TITLE
Polygons don't align cross-tiles 

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#48]
<img width="553" alt="Screenshot 2023-12-01 at 10 40 00 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/237841c5-7ca9-406f-a120-11477d5e214b">

**Comment by slz4025** [comment]
Potential solutions if (2) is the issue:
1. The polygonization is done on the entire area at once, and then vectorization takes places per-tile.
2. After vectorization, have points on the tile edge from both tiles line up.
3. After polygonization but before vectorization, have points on the tile edge from both tiles line up.

**Comment by slz4025** [comment]
Solution #1 to issue #2 is guaranteed to work. The main issue is that at least the polygonization step will require the entire raster to be effectively in-memory. I wonder if there is a way to do this if the machine has limited memory compared to the image size.

**Comment by slz4025** [comment]
Thinking more about this, the polygonization step should actually not be an issue either because it is using the given raster. All the supposed mis-alignment at the tile border is likely the result of pixelation offsets as the boundary of an area diagonally crosses the border.
