### ISSUE TITLE
Tile stitching is broken

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#57]
When run on a large region, the tiles were created correctly. However, the final stitched version of the file is clearly incorrect: 

<img width="689" alt="Screenshot 2023-12-08 at 7 25 00 PM" src="https://github.com/rainflame/geopolygonize/assets/20147175/a50e8c9a-2225-493a-8a87-3809da76c824">

**Comment by cbroms** [comment]
There are 2625 tiles, each approximately 100kb.

**Comment by slz4025** [comment]
Addressed by #58
