### ISSUE TITLE
Auto-detect pixel size

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#6]
When run on [this input](https://drive.google.com/file/d/18so7pH_7lZtOGQKXtcI-6_q35QmBPoAB/view?usp=drive_link), it produces this:

<img width="756" alt="Screenshot 2023-11-19 at 6 40 05 AM" src="https://github.com/rainflame/geopolygonize/assets/20147175/3b8e6073-5491-4144-ac81-86879329deb1">

The coordinates and scale seem to be off as well. 

Command run, for reference: 

```
geopolygonize --input-file="data/quantized.tif" --output-file="data/contours.shp"
```

**Comment by cbroms** [comment]
This issue was caused by the fact that the pixel size of the input was 0.008333333333333334952, not 30. The pixel size will vary significantly depending on the projection of the input raster. 

We should auto-detect the pixel size if possible so the user doesn't have to supply it. It's also not always going to be in meters so we should change the name of the parameter in the CLI.

**Comment by slz4025** [comment]
`pixel_size` and `res` should be the same variable. We ask users to input a `pixel_size` when the `res` cannot be automatically inferred.

**Comment by slz4025** [comment]
Addressed by [PR](https://github.com/rainflame/geopolygonize/pull/20).
