### ISSUE TITLE
Fill in nodata pixels

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#61]
Some pixels are marked as `nodata` and should be filled in with the average of the pixels around them, like what happens in the blobbification step. Otherwise there will be polygons in the output that don't represent anything (such as border regions, or areas that have been prefiltered out). 

You can determine which pixel values are `nodata` by reading `src.nodata` after opening the raster with rasterio. This will likely be something like 0, -1, or 9999. Pixels with those values should then be optionally filled in by the tool.

**Comment by slz4025** [comment]
Addressed by #69
