### ISSUE TITLE
Decide on approach to multi-resolution outputs

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#63]
We need a way to create multiple versions of the same region for use at different zoom levels. When zoomed out, the polygons should be fewer and more simplified to keep tile size down. Small polygon areas should be removed. 

The approach we discussed was to first increase the pixel size, then run geopolygonize. Another approach is to try increasing the blob size to remove small areas. In either case, it would be good to have an efficient way to generate 4-5 versions of the output at different zoom levels, with increasing resolution.

**Comment by slz4025** [comment]
Resolved via #64.
